-- ==================== SETUP MULTI-TENANT - CONTROLE DE ESTACIONAMENTO ====================
-- Execute no SQL Editor do Supabase: https://app.supabase.com/project/_/sql
-- Este script cria a estrutura multi-tenant necessária

-- ==================== 1. TABELA: CLIENTES ====================
CREATE TABLE IF NOT EXISTS clientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razao_social VARCHAR(200) NOT NULL,
  nome_fantasia VARCHAR(200),
  ativo BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==================== 2. ADICIONAR cliente_id NAS TABELAS EXISTENTES ====================

-- Usuários
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS nome VARCHAR(200);
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS ativo BOOLEAN NOT NULL DEFAULT true;

-- Veículos
ALTER TABLE veiculos ADD COLUMN IF NOT EXISTS cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE;

-- Histórico
ALTER TABLE historico ADD COLUMN IF NOT EXISTS cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE;

-- ==================== 3. ÍNDICES ====================
CREATE INDEX IF NOT EXISTS idx_usuarios_cliente ON usuarios(cliente_id);
CREATE INDEX IF NOT EXISTS idx_veiculos_cliente ON veiculos(cliente_id);
CREATE INDEX IF NOT EXISTS idx_historico_cliente ON historico(cliente_id);

-- ==================== 4. ROW LEVEL SECURITY (RLS) ====================
ALTER TABLE clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE veiculos ENABLE ROW LEVEL SECURITY;
ALTER TABLE historico ENABLE ROW LEVEL SECURITY;

-- Drop políticas existentes
DROP POLICY IF EXISTS "Acesso total - clientes" ON clientes;
DROP POLICY IF EXISTS "Acesso total - usuarios" ON usuarios;
DROP POLICY IF EXISTS "Acesso total - veiculos" ON veiculos;
DROP POLICY IF EXISTS "Acesso total - historico" ON historico;

-- Criar políticas (acesso total para desenvolvimento)
CREATE POLICY "Acesso total - clientes" ON clientes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acesso total - usuarios" ON usuarios FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acesso total - veiculos" ON veiculos FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acesso total - historico" ON historico FOR ALL USING (true) WITH CHECK (true);

-- ==================== 5. DADOS INICIAIS ====================

-- Cliente padrão (ID 1)
INSERT INTO clientes (id, razao_social, nome_fantasia, ativo)
VALUES (1, 'Cliente Padrão', 'Estacionamento Central', true)
ON CONFLICT (id) DO NOTHING;

-- Usuário admin para o cliente padrão (se não existir)
INSERT INTO usuarios (cliente_id, usuario, senha, nome, ativo)
VALUES (1, 'admin', 'admin', 'Administrador', true)
ON CONFLICT (usuario) DO UPDATE SET cliente_id = 1;

-- ==================== CONFIRMAÇÃO ====================
DO $$
BEGIN
  RAISE NOTICE '✅ Setup multi-tenant concluído!';
  RAISE NOTICE '📊 Tabela clientes criada';
  RAISE NOTICE '🔗 cliente_id adicionado em todas as tabelas';
  RAISE NOTICE '🔐 RLS habilitado';
  RAISE NOTICE '👤 Cliente padrão (ID 1) configurado';
  RAISE NOTICE '💡 Agora você pode cadastrar novos clientes pela tela de login';
END $$;
