-- ==================== SCHEMA MULTI-TENANT - CONTROLE DE ESTACIONAMENTO ====================
-- Execute este script no SQL Editor do Supabase: https://app.supabase.com/project/_/sql
-- Este script atualiza o schema existente para suportar múltiplos clientes

-- ==================== TABELA: CLIENTES ====================
CREATE TABLE IF NOT EXISTS clientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cnpj VARCHAR(20),
  razao_social VARCHAR(200) NOT NULL,
  nome_fantasia VARCHAR(200) NOT NULL UNIQUE,
  email VARCHAR(200),
  telefone VARCHAR(30),
  endereco TEXT,
  ativo BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Índice para busca por cliente
CREATE INDEX IF NOT EXISTS idx_clientes_ativo ON clientes(ativo) WHERE ativo = true;
CREATE UNIQUE INDEX IF NOT EXISTS idx_clientes_nome_fantasia ON clientes(nome_fantasia) WHERE ativo = true;

-- Comentário
COMMENT ON TABLE clientes IS 'Clientes/Estacionamentos que usam o sistema';

-- ==================== TABELA: USUÁRIOS (atualizada) ====================
-- Adicionar coluna cliente_id se não existir
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS nome VARCHAR(200);
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS email VARCHAR(200);
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS ativo BOOLEAN NOT NULL DEFAULT true;

-- Índice para busca por cliente
CREATE INDEX IF NOT EXISTS idx_usuarios_cliente ON usuarios(cliente_id);
CREATE INDEX IF NOT EXISTS idx_usuarios_ativo ON usuarios(ativo) WHERE ativo = true;

-- Constraint única para usuario por cliente (evita usuários duplicados no mesmo cliente)
ALTER TABLE usuarios DROP CONSTRAINT IF EXISTS usuarios_cliente_usuario_unique;
ALTER TABLE usuarios ADD CONSTRAINT usuarios_cliente_usuario_unique UNIQUE (cliente_id, usuario);

-- ==================== TABELA: VEÍCULOS (atualizada) ====================
-- Adicionar coluna cliente_id se não existir
ALTER TABLE veiculos ADD COLUMN IF NOT EXISTS cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE;

-- Índice para filtrar por cliente
CREATE INDEX IF NOT EXISTS idx_veiculos_cliente ON veiculos(cliente_id);
CREATE INDEX IF NOT EXISTS idx_veiculos_cliente_no_patio ON veiculos(cliente_id, saida) WHERE saida IS NULL;

-- ==================== TABELA: HISTÓRICO (atualizada) ====================
-- Adicionar coluna cliente_id se não existir
ALTER TABLE historico ADD COLUMN IF NOT EXISTS cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE;

-- Índice para filtrar por cliente
CREATE INDEX IF NOT EXISTS idx_historico_cliente ON historico(cliente_id);
CREATE INDEX IF NOT EXISTS idx_historico_cliente_saida ON historico(cliente_id, saida DESC);

-- ==================== TABELA: CONFIGURAÇÕES (atualizada) ====================
-- Remover constraint de linha única se existir (para permitir múltiplos clientes)
ALTER TABLE configuracoes DROP CONSTRAINT IF EXISTS configuracoes_single_row;

-- Adicionar colunas para múltiplos clientes
ALTER TABLE configuracoes ADD COLUMN IF NOT EXISTS cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE;
ALTER TABLE configuracoes ADD COLUMN IF NOT EXISTS valor_hora_adicional DECIMAL(10,2) DEFAULT 0;
ALTER TABLE configuracoes ADD COLUMN IF NOT EXISTS tolerancia_minutos INTEGER DEFAULT 0;

-- Criar constraint única por cliente
ALTER TABLE configuracoes DROP CONSTRAINT IF EXISTS configuracoes_cliente_unique;
ALTER TABLE configuracoes ADD CONSTRAINT configuracoes_cliente_unique UNIQUE (cliente_id);

-- Índice para busca por cliente
CREATE INDEX IF NOT EXISTS idx_configuracoes_cliente ON configuracoes(cliente_id);

-- ==================== TABELA: LOGS DE ACESSO (nova) ====================
CREATE TABLE IF NOT EXISTS logs_acesso (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE,
  usuario VARCHAR(100),
  acao VARCHAR(50),
  descricao TEXT,
  ip_address VARCHAR(50),
  user_agent TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Índice para logs por cliente
CREATE INDEX IF NOT EXISTS idx_logs_cliente ON logs_acesso(cliente_id);
CREATE INDEX IF NOT EXISTS idx_logs_data ON logs_acesso(created_at DESC);

-- ==================== FUNÇÃO: OBTER ID DO CLIENTE ATUAL ====================
-- Em produção, use JWT ou outro método para obter o cliente_id da sessão
-- Por enquanto, usaremos uma variável de sessão

-- ==================== POLÍTICAS DE RLS ATUALIZADAS ====================
-- Habilitar RLS (se ainda não estiver habilitado)
ALTER TABLE clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE veiculos ENABLE ROW LEVEL SECURITY;
ALTER TABLE historico ENABLE ROW LEVEL SECURITY;
ALTER TABLE configuracoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE logs_acesso ENABLE ROW LEVEL SECURITY;

-- Drop políticas existentes se houver
DROP POLICY IF EXISTS "Acesso total a clientes" ON clientes;
DROP POLICY IF EXISTS "Acesso total a usuarios" ON usuarios;
DROP POLICY IF EXISTS "Acesso total a veiculos" ON veiculos;
DROP POLICY IF EXISTS "Acesso total a historico" ON historico;
DROP POLICY IF EXISTS "Acesso total a configuracoes" ON configuracoes;
DROP POLICY IF EXISTS "Acesso total a logs_acesso" ON logs_acesso;

-- Políticas com filtro por cliente (em produção, use auth.jwt() para pegar o cliente_id)
-- Para desenvolvimento, permitimos acesso total mas com estrutura para multi-tenant

-- Política para clientes (apenas clientes ativos)
CREATE POLICY "Acesso a clientes" ON clientes
  FOR ALL USING (ativo = true);

-- Política para usuarios (filtra por cliente_id)
CREATE POLICY "Acesso a usuarios" ON usuarios
  FOR ALL USING (
    cliente_id IS NULL OR 
    cliente_id IN (SELECT id FROM clientes WHERE ativo = true)
  );

-- Política para veiculos (filtra por cliente_id)
CREATE POLICY "Acesso a veiculos" ON veiculos
  FOR ALL USING (
    cliente_id IS NULL OR 
    cliente_id IN (SELECT id FROM clientes WHERE ativo = true)
  );

-- Política para historico (filtra por cliente_id)
CREATE POLICY "Acesso a historico" ON historico
  FOR ALL USING (
    cliente_id IS NULL OR 
    cliente_id IN (SELECT id FROM clientes WHERE ativo = true)
  );

-- Política para configuracoes (filtra por cliente_id)
CREATE POLICY "Acesso a configuracoes" ON configuracoes
  FOR ALL USING (
    cliente_id IS NULL OR 
    cliente_id IN (SELECT id FROM clientes WHERE ativo = true)
  );

-- Política para logs_acesso (filtra por cliente_id)
CREATE POLICY "Acesso a logs_acesso" ON logs_acesso
  FOR ALL USING (
    cliente_id IS NULL OR 
    cliente_id IN (SELECT id FROM clientes WHERE ativo = true)
  );

-- ==================== FUNÇÕES UTILITÁRIAS ====================

-- Função para criar novo cliente com configurações padrão
CREATE OR REPLACE FUNCTION criar_cliente(
  p_cnpj VARCHAR(20),
  p_razao_social VARCHAR(200),
  p_nome_fantasia VARCHAR(200),
  p_email VARCHAR(200),
  p_telefone VARCHAR(30),
  p_endereco TEXT,
  p_usuario_admin VARCHAR(50),
  p_senha_admin VARCHAR(200)
) RETURNS BIGINT AS $$
DECLARE
  v_cliente_id BIGINT;
BEGIN
  -- Inserir cliente
  INSERT INTO clientes (cnpj, razao_social, nome_fantasia, email, telefone, endereco)
  VALUES (p_cnpj, p_razao_social, p_nome_fantasia, p_email, p_telefone, p_endereco)
  RETURNING id INTO v_cliente_id;
  
  -- Inserir configurações padrão
  INSERT INTO configuracoes (cliente_id, valor_hora_carro, valor_hora_moto, valor_hora_caminhao, total_vagas, nome_estacionamento)
  VALUES (v_cliente_id, 10.00, 5.00, 20.00, 20, COALESCE(p_nome_fantasia, p_razao_social));
  
  -- Inserir usuário admin
  INSERT INTO usuarios (cliente_id, usuario, senha, nome, email, ativo)
  VALUES (v_cliente_id, p_usuario_admin, p_senha_admin, 'Administrador', p_email, true);
  
  RETURN v_cliente_id;
END;
$$ LANGUAGE plpgsql;

-- Função para listar todos os clientes
CREATE OR REPLACE FUNCTION listar_clientes()
RETURNS TABLE (
  id BIGINT,
  cnpj VARCHAR(20),
  razao_social VARCHAR(200),
  nome_fantasia VARCHAR(200),
  email VARCHAR(200),
  telefone VARCHAR(30),
  ativo BOOLEAN,
  total_veiculos BIGINT,
  total_usuarios BIGINT
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    c.id,
    c.cnpj,
    c.razao_social,
    c.nome_fantasia,
    c.email,
    c.telefone,
    c.ativo,
    COALESCE(v.total, 0) AS total_veiculos,
    COALESCE(u.total, 0) AS total_usuarios
  FROM clientes c
  LEFT JOIN (
    SELECT cliente_id, COUNT(*) AS total
    FROM veiculos
    WHERE saida IS NULL
    GROUP BY cliente_id
  ) v ON c.id = v.cliente_id
  LEFT JOIN (
    SELECT cliente_id, COUNT(*) AS total
    FROM usuarios
    GROUP BY cliente_id
  ) u ON c.id = u.cliente_id
  ORDER BY c.razao_social;
END;
$$ LANGUAGE plpgsql;

-- ==================== DADOS INICIAIS ====================

-- Inserir cliente padrão (se não existir)
INSERT INTO clientes (cnpj, razao_social, nome_fantasia, email, telefone)
VALUES ('00.000.000/0001-00', 'Cliente Padrão Ltda', 'Estacionamento Central', 'contato@estacionamento.com', '(11) 99999-9999')
ON CONFLICT DO NOTHING;

-- Inserir configurações para o cliente padrão (id = 1)
INSERT INTO configuracoes (cliente_id, valor_hora_carro, valor_hora_moto, valor_hora_caminhao, total_vagas, nome_estacionamento)
VALUES (1, 10.00, 5.00, 20.00, 20, 'Estacionamento Central')
ON CONFLICT (cliente_id) DO NOTHING;

-- Inserir usuário admin para o cliente padrão (se não existir)
INSERT INTO usuarios (cliente_id, usuario, senha, nome, ativo)
VALUES (1, 'admin', 'admin', 'Administrador', true)
ON CONFLICT (usuario) DO UPDATE SET cliente_id = 1;

-- ==================== TRIGGERS ====================

-- Trigger para atualizar updated_at em clientes
DROP TRIGGER IF EXISTS update_clientes_updated_at ON clientes;
CREATE TRIGGER update_clientes_updated_at
  BEFORE UPDATE ON clientes
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ==================== VISÕES ====================

-- Visão de resumo por cliente
CREATE OR REPLACE VIEW resumo_multi_cliente AS
SELECT 
  c.id AS cliente_id,
  c.nome_fantasia,
  c.razao_social,
  c.ativo,
  COUNT(DISTINCT v.id) FILTER (WHERE v.saida IS NULL) AS veiculos_no_patio,
  COUNT(DISTINCT v.vaga) FILTER (WHERE v.saida IS NULL) AS vagas_ocupadas,
  cfg.total_vagas,
  cfg.total_vagas - COUNT(DISTINCT v.vaga) FILTER (WHERE v.saida IS NULL) AS vagas_livres,
  COUNT(DISTINCT h.id) FILTER (WHERE h.saida >= DATE_TRUNC('month', NOW())) AS saidas_mes,
  COALESCE(SUM(h.valor_cobrado) FILTER (WHERE h.saida >= DATE_TRUNC('month', NOW())), 0) AS faturamento_mes
FROM clientes c
LEFT JOIN veiculos v ON c.id = v.cliente_id
LEFT JOIN configuracoes cfg ON c.id = cfg.cliente_id
LEFT JOIN historico h ON c.id = h.cliente_id
GROUP BY c.id, c.nome_fantasia, c.razao_social, c.ativo, cfg.total_vagas;

-- ==================== MENSAGEM DE CONFIRMAÇÃO ====================
DO $$
BEGIN
  RAISE NOTICE '✅ Schema multi-tenant atualizado com sucesso!';
  RAISE NOTICE '📊 Tabelas atualizadas: clientes, usuarios, veiculos, historico, configuracoes, logs_acesso';
  RAISE NOTICE '🔐 RLS habilitado com filtro por cliente_id';
  RAISE NOTICE '🏢 Cliente padrão criado (ID: 1)';
  RAISE NOTICE '💡 Use a função criar_cliente() para adicionar novos clientes';
  RAISE NOTICE '💡 Consulte listar_clientes() para ver todos os clientes';
END $$;
