-- ==================== SCHEMA COMPLETO - CONTROLE DE ESTACIONAMENTO ====================
-- Execute este script no SQL Editor do Supabase: https://app.supabase.com/project/_/sql
-- Este script cria todas as tabelas do zero de forma correta

-- ==================== 1. TABELA: USUÁRIOS (LOGIN) ====================
CREATE TABLE IF NOT EXISTS usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario VARCHAR(50) UNIQUE NOT NULL,
  senha VARCHAR(200) NOT NULL,
  nome VARCHAR(200),
  email VARCHAR(200),
  ativo BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Índice para login
CREATE INDEX IF NOT EXISTS idx_usuarios_usuario ON usuarios(usuario) WHERE ativo = true;

-- Inserir usuário admin padrão (senha: admin)
INSERT INTO usuarios (usuario, senha, nome, ativo)
VALUES ('admin', 'admin', 'Administrador', true)
ON CONFLICT (usuario) DO NOTHING;

-- ==================== 2. TABELA: VEÍCULOS NO PÁTIO ====================
CREATE TABLE IF NOT EXISTS veiculos (
  id BIGINT PRIMARY KEY,
  placa VARCHAR(20) NOT NULL,
  marca VARCHAR(100) NOT NULL,
  modelo VARCHAR(100) NOT NULL,
  cor VARCHAR(50),
  tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('carro', 'moto', 'caminhao')),
  proprietario VARCHAR(200),
  telefone VARCHAR(30),
  vaga VARCHAR(10) NOT NULL,
  entrada TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  saida TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Índices para busca
CREATE INDEX IF NOT EXISTS idx_veiculos_placa ON veiculos(placa);
CREATE INDEX IF NOT EXISTS idx_veiculos_no_patio ON veiculos(saida) WHERE saida IS NULL;

-- ==================== 3. TABELA: HISTÓRICO ====================
CREATE TABLE IF NOT EXISTS historico (
  id BIGINT PRIMARY KEY,
  veiculo_id BIGINT,
  placa VARCHAR(20) NOT NULL,
  marca VARCHAR(100) NOT NULL,
  modelo VARCHAR(100) NOT NULL,
  cor VARCHAR(50),
  tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('carro', 'moto', 'caminhao')),
  proprietario VARCHAR(200),
  telefone VARCHAR(30),
  vaga VARCHAR(10) NOT NULL,
  entrada TIMESTAMP WITH TIME ZONE NOT NULL,
  saida TIMESTAMP WITH TIME ZONE NOT NULL,
  tempo_permanencia VARCHAR(20),
  valor_cobrado DECIMAL(10,2) NOT NULL DEFAULT 0,
  forma_pagamento VARCHAR(20) NOT NULL CHECK (forma_pagamento IN ('dinheiro', 'pix', 'cartao')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Índices para busca
CREATE INDEX IF NOT EXISTS idx_historico_placa ON historico(placa);
CREATE INDEX IF NOT EXISTS idx_historico_saida ON historico(saida DESC);

-- ==================== 4. TABELA: CONFIGURAÇÕES ====================
CREATE TABLE IF NOT EXISTS configuracoes (
  id INTEGER PRIMARY KEY DEFAULT 1,
  valor_hora_carro DECIMAL(10,2) NOT NULL DEFAULT 10.00,
  valor_hora_moto DECIMAL(10,2) NOT NULL DEFAULT 5.00,
  valor_hora_caminhao DECIMAL(10,2) NOT NULL DEFAULT 20.00,
  total_vagas INTEGER NOT NULL DEFAULT 20,
  nome_estacionamento VARCHAR(200) NOT NULL DEFAULT 'Estacionamento Central',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT configuracoes_single_row CHECK (id = 1)
);

-- Inserir configuração padrão
INSERT INTO configuracoes (id, valor_hora_carro, valor_hora_moto, valor_hora_caminhao, total_vagas, nome_estacionamento)
VALUES (1, 10.00, 5.00, 20.00, 20, 'Estacionamento Central')
ON CONFLICT (id) DO NOTHING;

-- ==================== 5. TRIGGER: ATUALIZAR updated_at ====================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_veiculos_updated_at ON veiculos;
CREATE TRIGGER update_veiculos_updated_at
  BEFORE UPDATE ON veiculos
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_configuracoes_updated_at ON configuracoes;
CREATE TRIGGER update_configuracoes_updated_at
  BEFORE UPDATE ON configuracoes
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_usuarios_updated_at ON usuarios;
CREATE TRIGGER update_usuarios_updated_at
  BEFORE UPDATE ON usuarios
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ==================== 6. ROW LEVEL SECURITY (RLS) ====================
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE veiculos ENABLE ROW LEVEL SECURITY;
ALTER TABLE historico ENABLE ROW LEVEL SECURITY;
ALTER TABLE configuracoes ENABLE ROW LEVEL SECURITY;

-- Drop políticas existentes
DROP POLICY IF EXISTS "Acesso total - usuarios" ON usuarios;
DROP POLICY IF EXISTS "Acesso total - veiculos" ON veiculos;
DROP POLICY IF EXISTS "Acesso total - historico" ON historico;
DROP POLICY IF EXISTS "Acesso total - configuracoes" ON configuracoes;

-- Criar políticas de acesso total (para desenvolvimento)
CREATE POLICY "Acesso total - usuarios" ON usuarios FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acesso total - veiculos" ON veiculos FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acesso total - historico" ON historico FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acesso total - configuracoes" ON configuracoes FOR ALL USING (true) WITH CHECK (true);

-- ==================== 7. COMENTÁRIOS ====================
COMMENT ON TABLE usuarios IS 'Usuários do sistema para login';
COMMENT ON TABLE veiculos IS 'Veículos estacionados no pátio';
COMMENT ON TABLE historico IS 'Histórico de veículos que já saíram';
COMMENT ON TABLE configuracoes IS 'Configurações do sistema';

COMMENT ON COLUMN veiculos.tipo IS 'Tipo: carro, moto ou caminhao';
COMMENT ON COLUMN veiculos.entrada IS 'Data/hora da entrada';
COMMENT ON COLUMN veiculos.saida IS 'Data/hora da saída (NULL = no pátio)';
COMMENT ON COLUMN historico.forma_pagamento IS 'Forma: dinheiro, pix ou cartao';

-- ==================== 8. VISÃO: RESUMO DO PÁTIO ====================
CREATE OR REPLACE VIEW resumo_patio AS
SELECT
  COUNT(*) AS total_veiculos,
  COUNT(*) FILTER (WHERE tipo = 'carro') AS total_carros,
  COUNT(*) FILTER (WHERE tipo = 'moto') AS total_motos,
  COUNT(*) FILTER (WHERE tipo = 'caminhao') AS total_caminhoes,
  (SELECT total_vagas FROM configuracoes WHERE id = 1) AS total_vagas,
  (SELECT total_vagas FROM configuracoes WHERE id = 1) - COUNT(*) AS vagas_livres
FROM veiculos
WHERE saida IS NULL;

-- ==================== CONFIRMAÇÃO ====================
DO $$
BEGIN
  RAISE NOTICE '✅ Schema criado com sucesso!';
  RAISE NOTICE '📊 Tabelas: usuarios, veiculos, historico, configuracoes';
  RAISE NOTICE '🔐 RLS habilitado com acesso total';
  RAISE NOTICE '👤 Usuário admin: admin / admin';
  RAISE NOTICE '⚙️ Configuração padrão: 10 vagas, R$10/h carro';
END $$;
