-- ==================== SCHEMA COMPLETO - MULTI-TENANT ====================
-- Este script cria todas as tabelas já com suporte multi-tenant
-- Execute no SQL Editor do Supabase: https://app.supabase.com/project/_/sql

-- ==================== TABELA: CLIENTES ====================
CREATE TABLE IF NOT EXISTS clientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cnpj VARCHAR(20),
  razao_social VARCHAR(200) NOT NULL,
  nome_fantasia VARCHAR(200),
  email VARCHAR(200),
  telefone VARCHAR(30),
  endereco TEXT,
  ativo BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_clientes_ativo ON clientes(ativo) WHERE ativo = true;

COMMENT ON TABLE clientes IS 'Clientes/Estacionamentos que usam o sistema';

-- ==================== TABELA: USUÁRIOS ====================
CREATE TABLE IF NOT EXISTS usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE,
  usuario VARCHAR(50) NOT NULL,
  senha VARCHAR(200) NOT NULL,
  nome VARCHAR(200),
  email VARCHAR(200),
  ativo BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_usuarios_cliente ON usuarios(cliente_id);
CREATE INDEX IF NOT EXISTS idx_usuarios_usuario ON usuarios(usuario);
CREATE INDEX IF NOT EXISTS idx_usuarios_ativo ON usuarios(ativo) WHERE ativo = true;

-- ==================== TABELA: VEÍCULOS ====================
CREATE TABLE IF NOT EXISTS veiculos (
  id BIGINT PRIMARY KEY,
  cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE,
  placa VARCHAR(20) NOT NULL,
  marca VARCHAR(100) NOT NULL,
  modelo VARCHAR(100) NOT NULL,
  cor VARCHAR(50),
  tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('carro', 'moto', 'caminhao')),
  proprietario VARCHAR(200),
  telefone VARCHAR(30),
  vaga VARCHAR(10) NOT NULL,
  entrada TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  saida TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_veiculos_placa ON veiculos(placa);
CREATE INDEX IF NOT EXISTS idx_veiculos_cliente ON veiculos(cliente_id);
CREATE INDEX IF NOT EXISTS idx_veiculos_cliente_no_patio ON veiculos(cliente_id, saida) WHERE saida IS NULL;

-- ==================== TABELA: HISTÓRICO ====================
CREATE TABLE IF NOT EXISTS historico (
  id BIGINT PRIMARY KEY,
  cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE,
  veiculo_id BIGINT,
  placa VARCHAR(20) NOT NULL,
  marca VARCHAR(100) NOT NULL,
  modelo VARCHAR(100) NOT NULL,
  cor VARCHAR(50),
  tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('carro', 'moto', 'caminhao')),
  proprietario VARCHAR(200),
  telefone VARCHAR(30),
  vaga VARCHAR(10) NOT NULL,
  entrada TIMESTAMP WITH TIME ZONE NOT NULL,
  saida TIMESTAMP WITH TIME ZONE NOT NULL,
  tempo_permanencia VARCHAR(20),
  valor_cobrado DECIMAL(10,2) NOT NULL DEFAULT 0,
  forma_pagamento VARCHAR(20) NOT NULL CHECK (forma_pagamento IN ('dinheiro', 'pix', 'cartao')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_historico_placa ON historico(placa);
CREATE INDEX IF NOT EXISTS idx_historico_cliente ON historico(cliente_id);
CREATE INDEX IF NOT EXISTS idx_historico_cliente_saida ON historico(cliente_id, saida DESC);

-- ==================== TABELA: CONFIGURAÇÕES ====================
CREATE TABLE IF NOT EXISTS configuracoes (
  id INTEGER NOT NULL,
  cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE,
  valor_hora_carro DECIMAL(10,2) NOT NULL DEFAULT 10.00,
  valor_hora_moto DECIMAL(10,2) NOT NULL DEFAULT 5.00,
  valor_hora_caminhao DECIMAL(10,2) NOT NULL DEFAULT 20.00,
  total_vagas INTEGER NOT NULL DEFAULT 20,
  nome_estacionamento VARCHAR(200) NOT NULL DEFAULT 'Estacionamento Central',
  valor_hora_adicional DECIMAL(10,2) DEFAULT 0,
  tolerancia_minutos INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT configuracoes_cliente_unique UNIQUE (cliente_id)
);

CREATE INDEX IF NOT EXISTS idx_configuracoes_cliente ON configuracoes(cliente_id);

-- ==================== TABELA: LOGS DE ACESSO ====================
CREATE TABLE IF NOT EXISTS logs_acesso (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE,
  usuario VARCHAR(100),
  acao VARCHAR(50),
  descricao TEXT,
  ip_address VARCHAR(50),
  user_agent TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_logs_cliente ON logs_acesso(cliente_id);
CREATE INDEX IF NOT EXISTS idx_logs_data ON logs_acesso(created_at DESC);

-- ==================== FUNÇÃO: UPDATE UPDATED_AT ====================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ==================== TRIGGERS ====================
DROP TRIGGER IF EXISTS update_clientes_updated_at ON clientes;
CREATE TRIGGER update_clientes_updated_at
  BEFORE UPDATE ON clientes
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_usuarios_updated_at ON usuarios;
CREATE TRIGGER update_usuarios_updated_at
  BEFORE UPDATE ON usuarios
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_veiculos_updated_at ON veiculos;
CREATE TRIGGER update_veiculos_updated_at
  BEFORE UPDATE ON veiculos
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_configuracoes_updated_at ON configuracoes;
CREATE TRIGGER update_configuracoes_updated_at
  BEFORE UPDATE ON configuracoes
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ==================== ROW LEVEL SECURITY (RLS) ====================
ALTER TABLE clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE veiculos ENABLE ROW LEVEL SECURITY;
ALTER TABLE historico ENABLE ROW LEVEL SECURITY;
ALTER TABLE configuracoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE logs_acesso ENABLE ROW LEVEL SECURITY;

-- Drop políticas existentes
DROP POLICY IF EXISTS "Acesso a clientes" ON clientes;
DROP POLICY IF EXISTS "Acesso a usuarios" ON usuarios;
DROP POLICY IF EXISTS "Acesso a veiculos" ON veiculos;
DROP POLICY IF EXISTS "Acesso a historico" ON historico;
DROP POLICY IF EXISTS "Acesso a configuracoes" ON configuracoes;
DROP POLICY IF EXISTS "Acesso a logs_acesso" ON logs_acesso;

-- Políticas com filtro por cliente
CREATE POLICY "Acesso a clientes" ON clientes
  FOR ALL USING (ativo = true);

CREATE POLICY "Acesso a usuarios" ON usuarios
  FOR ALL USING (
    cliente_id IS NULL OR 
    cliente_id IN (SELECT id FROM clientes WHERE ativo = true)
  );

CREATE POLICY "Acesso a veiculos" ON veiculos
  FOR ALL USING (
    cliente_id IS NULL OR 
    cliente_id IN (SELECT id FROM clientes WHERE ativo = true)
  );

CREATE POLICY "Acesso a historico" ON historico
  FOR ALL USING (
    cliente_id IS NULL OR 
    cliente_id IN (SELECT id FROM clientes WHERE ativo = true)
  );

CREATE POLICY "Acesso a configuracoes" ON configuracoes
  FOR ALL USING (
    cliente_id IS NULL OR 
    cliente_id IN (SELECT id FROM clientes WHERE ativo = true)
  );

CREATE POLICY "Acesso a logs_acesso" ON logs_acesso
  FOR ALL USING (
    cliente_id IS NULL OR 
    cliente_id IN (SELECT id FROM clientes WHERE ativo = true)
  );

-- ==================== FUNÇÃO: CRIAR CLIENTE ====================
CREATE OR REPLACE FUNCTION criar_cliente(
  p_cnpj VARCHAR(20),
  p_razao_social VARCHAR(200),
  p_nome_fantasia VARCHAR(200),
  p_email VARCHAR(200),
  p_telefone VARCHAR(30),
  p_endereco TEXT,
  p_usuario_admin VARCHAR(50),
  p_senha_admin VARCHAR(200)
) RETURNS BIGINT AS $$
DECLARE
  v_cliente_id BIGINT;
BEGIN
  -- Inserir cliente
  INSERT INTO clientes (cnpj, razao_social, nome_fantasia, email, telefone, endereco)
  VALUES (p_cnpj, p_razao_social, p_nome_fantasia, p_email, p_telefone, p_endereco)
  RETURNING id INTO v_cliente_id;
  
  -- Inserir configurações padrão
  INSERT INTO configuracoes (cliente_id, valor_hora_carro, valor_hora_moto, valor_hora_caminhao, total_vagas, nome_estacionamento)
  VALUES (v_cliente_id, 10.00, 5.00, 20.00, 20, COALESCE(p_nome_fantasia, p_razao_social));
  
  -- Inserir usuário admin
  INSERT INTO usuarios (cliente_id, usuario, senha, nome, email, ativo)
  VALUES (v_cliente_id, p_usuario_admin, p_senha_admin, 'Administrador', p_email, true);
  
  RETURN v_cliente_id;
END;
$$ LANGUAGE plpgsql;

-- ==================== FUNÇÃO: LISTAR CLIENTES ====================
CREATE OR REPLACE FUNCTION listar_clientes()
RETURNS TABLE (
  id BIGINT,
  cnpj VARCHAR(20),
  razao_social VARCHAR(200),
  nome_fantasia VARCHAR(200),
  email VARCHAR(200),
  telefone VARCHAR(30),
  ativo BOOLEAN,
  total_veiculos BIGINT,
  total_usuarios BIGINT
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    c.id,
    c.cnpj,
    c.razao_social,
    c.nome_fantasia,
    c.email,
    c.telefone,
    c.ativo,
    COALESCE(v.total, 0) AS total_veiculos,
    COALESCE(u.total, 0) AS total_usuarios
  FROM clientes c
  LEFT JOIN (
    SELECT cliente_id, COUNT(*) AS total
    FROM veiculos
    WHERE saida IS NULL
    GROUP BY cliente_id
  ) v ON c.id = v.cliente_id
  LEFT JOIN (
    SELECT cliente_id, COUNT(*) AS total
    FROM usuarios
    GROUP BY cliente_id
  ) u ON c.id = u.cliente_id
  ORDER BY c.razao_social;
END;
$$ LANGUAGE plpgsql;

-- ==================== VISÃO: RESUMO MULTI-CLIENTE ====================
CREATE OR REPLACE VIEW resumo_multi_cliente AS
SELECT 
  c.id AS cliente_id,
  c.nome_fantasia,
  c.razao_social,
  c.ativo,
  COUNT(DISTINCT v.id) FILTER (WHERE v.saida IS NULL) AS veiculos_no_patio,
  COUNT(DISTINCT v.vaga) FILTER (WHERE v.saida IS NULL) AS vagas_ocupadas,
  cfg.total_vagas,
  cfg.total_vagas - COUNT(DISTINCT v.vaga) FILTER (WHERE v.saida IS NULL) AS vagas_livres,
  COUNT(DISTINCT h.id) FILTER (WHERE h.saida >= DATE_TRUNC('month', NOW())) AS saidas_mes,
  COALESCE(SUM(h.valor_cobrado) FILTER (WHERE h.saida >= DATE_TRUNC('month', NOW())), 0) AS faturamento_mes
FROM clientes c
LEFT JOIN veiculos v ON c.id = v.cliente_id
LEFT JOIN configuracoes cfg ON c.id = cfg.cliente_id
LEFT JOIN historico h ON c.id = h.cliente_id
GROUP BY c.id, c.nome_fantasia, c.razao_social, c.ativo, cfg.total_vagas;

-- ==================== DADOS INICIAIS ====================

-- Inserir cliente padrão (ID = 1)
INSERT INTO clientes (id, cnpj, razao_social, nome_fantasia, email, telefone)
VALUES (1, '00.000.000/0001-00', 'Cliente Padrão Ltda', 'Estacionamento Central', 'contato@estacionamento.com', '(11) 99999-9999')
ON CONFLICT (id) DO NOTHING;

-- Inserir configurações para o cliente padrão
INSERT INTO configuracoes (cliente_id, valor_hora_carro, valor_hora_moto, valor_hora_caminhao, total_vagas, nome_estacionamento)
VALUES (1, 10.00, 5.00, 20.00, 20, 'Estacionamento Central')
ON CONFLICT (cliente_id) DO NOTHING;

-- Inserir usuário admin para o cliente padrão
INSERT INTO usuarios (cliente_id, usuario, senha, nome, ativo)
VALUES (1, 'admin', 'admin', 'Administrador', 'contato@estacionamento.com', true)
ON CONFLICT DO NOTHING;

-- ==================== COMENTÁRIOS ====================
COMMENT ON TABLE veiculos IS 'Veículos estacionados no pátio';
COMMENT ON TABLE historico IS 'Histórico de veículos que já saíram';
COMMENT ON TABLE configuracoes IS 'Configurações do sistema de estacionamento';
COMMENT ON TABLE usuarios IS 'Usuários do sistema';
COMMENT ON TABLE logs_acesso IS 'Logs de acesso dos usuários';

COMMENT ON COLUMN veiculos.tipo IS 'Tipo de veículo: carro, moto ou caminhao';
COMMENT ON COLUMN veiculos.entrada IS 'Data/hora da entrada do veículo';
COMMENT ON COLUMN veiculos.saida IS 'Data/hora da saída (NULL = ainda no pátio)';
COMMENT ON COLUMN veiculos.cliente_id IS 'ID do cliente (multi-tenant)';

COMMENT ON COLUMN historico.forma_pagamento IS 'Forma de pagamento: dinheiro, pix ou cartao';
COMMENT ON COLUMN historico.tempo_permanencia IS 'Tempo de permanência formatado (ex: 2h 30min)';
COMMENT ON COLUMN historico.cliente_id IS 'ID do cliente (multi-tenant)';

-- ==================== MENSAGEM DE CONFIRMAÇÃO ====================
DO $$
BEGIN
  RAISE NOTICE '✅ Schema multi-tenant criado com sucesso!';
  RAISE NOTICE '📊 Tabelas criadas: clientes, usuarios, veiculos, historico, configuracoes, logs_acesso';
  RAISE NOTICE '🔐 RLS habilitado com filtro por cliente_id';
  RAISE NOTICE '🏢 Cliente padrão criado (ID: 1)';
  RAISE NOTICE '👤 Usuário admin criado (usuario: admin, senha: admin)';
  RAISE NOTICE '💡 Use criar_cliente() para adicionar novos clientes';
  RAISE NOTICE '💡 Use listar_clientes() para ver todos os clientes';
  RAISE NOTICE '💡 Consulte resumo_multi_cliente para visão geral';
END $$;
