-- ==================== SCHEMA DO BANCO DE DADOS - CONTROLE DE ESTACIONAMENTO ====================
-- Execute este script no SQL Editor do Supabase: https://app.supabase.com/project/_/sql

-- ==================== TABELA: VEÍCULOS NO PÁTIO ====================
CREATE TABLE IF NOT EXISTS veiculos (
  id BIGINT PRIMARY KEY,
  placa VARCHAR(20) NOT NULL,
  marca VARCHAR(100) NOT NULL,
  modelo VARCHAR(100) NOT NULL,
  cor VARCHAR(50),
  tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('carro', 'moto', 'caminhao')),
  proprietario VARCHAR(200),
  telefone VARCHAR(30),
  vaga VARCHAR(10) NOT NULL,
  entrada TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  saida TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Índice para busca por placa
CREATE INDEX IF NOT EXISTS idx_veiculos_placa ON veiculos(placa);

-- Índice para veículos no pátio (sem saída)
CREATE INDEX IF NOT EXISTS idx_veiculos_no_patio ON veiculos(saida) WHERE saida IS NULL;

-- ==================== TABELA: HISTÓRICO ====================
CREATE TABLE IF NOT EXISTS historico (
  id BIGINT PRIMARY KEY,
  veiculo_id BIGINT,
  placa VARCHAR(20) NOT NULL,
  marca VARCHAR(100) NOT NULL,
  modelo VARCHAR(100) NOT NULL,
  cor VARCHAR(50),
  tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('carro', 'moto', 'caminhao')),
  proprietario VARCHAR(200),
  telefone VARCHAR(30),
  vaga VARCHAR(10) NOT NULL,
  entrada TIMESTAMP WITH TIME ZONE NOT NULL,
  saida TIMESTAMP WITH TIME ZONE NOT NULL,
  tempo_permanencia VARCHAR(20),
  valor_cobrado DECIMAL(10,2) NOT NULL DEFAULT 0,
  forma_pagamento VARCHAR(20) NOT NULL CHECK (forma_pagamento IN ('dinheiro', 'pix', 'cartao')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Índice para busca por placa no histórico
CREATE INDEX IF NOT EXISTS idx_historico_placa ON historico(placa);

-- Índice para busca por período
CREATE INDEX IF NOT EXISTS idx_historico_saida ON historico(saida DESC);

-- ==================== TABELA: CONFIGURAÇÕES ====================
CREATE TABLE IF NOT EXISTS configuracoes (
  id INTEGER PRIMARY KEY DEFAULT 1,
  valor_hora_carro DECIMAL(10,2) NOT NULL DEFAULT 10.00,
  valor_hora_moto DECIMAL(10,2) NOT NULL DEFAULT 5.00,
  valor_hora_caminhao DECIMAL(10,2) NOT NULL DEFAULT 20.00,
  total_vagas INTEGER NOT NULL DEFAULT 20,
  nome_estacionamento VARCHAR(200) NOT NULL DEFAULT 'Estacionamento Central',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT configuracoes_single_row CHECK (id = 1)
);

-- Inserir configuração padrão
INSERT INTO configuracoes (id, valor_hora_carro, valor_hora_moto, valor_hora_caminhao, total_vagas, nome_estacionamento)
VALUES (1, 10.00, 5.00, 20.00, 20, 'Estacionamento Central')
ON CONFLICT (id) DO NOTHING;

-- ==================== TABELA: USUÁRIOS ====================
CREATE TABLE IF NOT EXISTS usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario VARCHAR(50) UNIQUE NOT NULL,
  senha VARCHAR(200) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Inserir usuário admin padrão (senha: admin)
-- ⚠️ Em produção, use hash de senha!
INSERT INTO usuarios (usuario, senha)
VALUES ('admin', 'admin')
ON CONFLICT (usuario) DO NOTHING;

-- Índice para busca por usuário
CREATE INDEX IF NOT EXISTS idx_usuarios_usuario ON usuarios(usuario);

-- ==================== TRIGGER: ATUALIZAR updated_at ====================
-- Função para atualizar o timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger para veiculos
DROP TRIGGER IF EXISTS update_veiculos_updated_at ON veiculos;
CREATE TRIGGER update_veiculos_updated_at
  BEFORE UPDATE ON veiculos
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Trigger para configuracoes
DROP TRIGGER IF EXISTS update_configuracoes_updated_at ON configuracoes;
CREATE TRIGGER update_configuracoes_updated_at
  BEFORE UPDATE ON configuracoes
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Trigger para usuarios
DROP TRIGGER IF EXISTS update_usuarios_updated_at ON usuarios;
CREATE TRIGGER update_usuarios_updated_at
  BEFORE UPDATE ON usuarios
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ==================== ROW LEVEL SECURITY (RLS) ====================
-- Habilitar RLS nas tabelas
ALTER TABLE veiculos ENABLE ROW LEVEL SECURITY;
ALTER TABLE historico ENABLE ROW LEVEL SECURITY;
ALTER TABLE configuracoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;

-- Políticas para permitir acesso total (em produção, personalize conforme necessário)
-- Política para veiculos
CREATE POLICY "Acesso total a veiculos" ON veiculos
  FOR ALL USING (true) WITH CHECK (true);

-- Política para historico
CREATE POLICY "Acesso total a historico" ON historico
  FOR ALL USING (true) WITH CHECK (true);

-- Política para configuracoes
CREATE POLICY "Acesso total a configuracoes" ON configuracoes
  FOR ALL USING (true) WITH CHECK (true);

-- Política para usuarios
CREATE POLICY "Acesso total a usuarios" ON usuarios
  FOR ALL USING (true) WITH CHECK (true);

-- ==================== COMENTÁRIOS NAS TABELAS ====================
COMMENT ON TABLE veiculos IS 'Veículos estacionados no pátio';
COMMENT ON TABLE historico IS 'Histórico de veículos que já saíram';
COMMENT ON TABLE configuracoes IS 'Configurações do sistema de estacionamento';
COMMENT ON TABLE usuarios IS 'Usuários do sistema';

COMMENT ON COLUMN veiculos.tipo IS 'Tipo de veículo: carro, moto ou caminhao';
COMMENT ON COLUMN veiculos.entrada IS 'Data/hora da entrada do veículo';
COMMENT ON COLUMN veiculos.saida IS 'Data/hora da saída (NULL = ainda no pátio)';

COMMENT ON COLUMN historico.forma_pagamento IS 'Forma de pagamento: dinheiro, pix ou cartao';
COMMENT ON COLUMN historico.tempo_permanencia IS 'Tempo de permanência formatado (ex: 2h 30min)';

-- ==================== VISÃO: RESUMO DO PÁTIO ====================
CREATE OR REPLACE VIEW resumo_patio AS
SELECT
  COUNT(*) AS total_veiculos,
  COUNT(*) FILTER (WHERE tipo = 'carro') AS total_carros,
  COUNT(*) FILTER (WHERE tipo = 'moto') AS total_motos,
  COUNT(*) FILTER (WHERE tipo = 'caminhao') AS total_caminhoes,
  (SELECT total_vagas FROM configuracoes WHERE id = 1) AS total_vagas,
  (SELECT total_vagas FROM configuracoes WHERE id = 1) - COUNT(*) AS vagas_livres
FROM veiculos
WHERE saida IS NULL;

-- ==================== DADOS INICIAIS ====================
-- Mensagem de confirmação
DO $$
BEGIN
  RAISE NOTICE '✅ Schema do banco de dados criado com sucesso!';
  RAISE NOTICE '📊 Tabelas criadas: veiculos, historico, configuracoes, usuarios';
  RAISE NOTICE '🔐 RLS habilitado com políticas de acesso total';
  RAISE NOTICE '⚙️ Configuração padrão inserida (ID: 1)';
  RAISE NOTICE '👤 Usuário admin padrão criado (usuario: admin, senha: admin)';
END $$;
